# -*- coding: utf-8 -*-
"""Path Loss and Throughput Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNgU7X8J-7yHvGuMy4MMdE3dtQHtQBxm
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

#Path Loss Dataset 1:
#Rural Dataframe:
DS1_Rural_df = pd.read_csv('/content/drive/MyDrive/Rural.csv')
DS1_Rural_df.head(10)

DS1_Rural_df = DS1_Rural_df[['Altitude', 'Distance (km)', 'near', 'bAzi', 'bEle', 'RSRP', 'SINR', 'Transmitted Power', 'Path Loss']]

DS1_Rural_df.head(10)

#Suburban Dataframe:
DS1_Suburban_df = pd.read_csv('/content/drive/MyDrive/Suburban.csv')
DS1_Suburban_df.head(10)

DS1_Suburban_df = DS1_Suburban_df[['Altitude', 'Distance (km)', 'near', 'bAzi', 'bEle', 'RSRP', 'SINR', 'Transmitted Power', 'Path Loss']]

#Urban Dataframe:
DS1_Urban_df = pd.read_csv('/content/drive/MyDrive/Urban.csv')
DS1_Urban_df.head(10)

DS1_Urban_df = DS1_Urban_df[['Altitude', 'Distance (km)', 'near', 'bAzi', 'bEle', 'RSRP', 'SINR', 'Transmitted power', 'Path Loss']]

#Path Loss Dataset 2:
#Baseball Park (Low Density) Dataframe:
DS2_Baseball_df = pd.read_csv('/content/drive/MyDrive/Baseball Park.csv')
DS2_Baseball_PL = pd.read_csv('/content/drive/MyDrive/Baseball Path Loss.csv')
DS2_Baseball_df.head(10)

DS2_Baseball_df['5G KPI PCell RF Pathloss [dB]'] = DS2_Baseball_PL['5G KPI PCell RF Pathloss [dB]'] #path loss wasn't showing up properly without this step

DS2_Baseball_df = DS2_Baseball_df[DS2_Baseball_df['5G KPI PCell RF Pathloss [dB]'].notna()]

DS2_Baseball_df = DS2_Baseball_df[['5G KPI PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell Serving RSRP[dBm]', 'LTE KPI PCell Serving RSRQ[dB]', '5G KPI PCell RF Serving SS-RSRQ [dB]', '5G KPI PCell RF Best Beam SS-RSRP [dBm]', '5G KPI PCell RF Pathloss [dB]']]
DS2_Baseball_df = DS2_Baseball_df.ffill()
DS2_Baseball_df = DS2_Baseball_df.dropna()

#City-Wide(Medium Density) Dataframe:
DS2_City_df = pd.read_csv('/content/drive/MyDrive/City-Wide.csv')
DS2_City_PL = pd.read_csv('/content/drive/MyDrive/City-Wide Loss.csv')
DS2_City_df.head(10)

DS2_City_df['5G KPI PCell RF Pathloss [dB]'] = DS2_City_PL['5G KPI PCell RF Pathloss [dB]']
DS2_City_df = DS2_City_df[DS2_City_df['5G KPI PCell RF Pathloss [dB]'].notna()]
DS2_City_df = DS2_City_df[['5G KPI PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell Serving RSRP[dBm]', 'LTE KPI PCell Serving RSRQ[dB]', '5G KPI PCell RF Serving SS-RSRQ [dB]', '5G KPI PCell RF Best Beam SS-RSRP [dBm]', '5G KPI PCell RF Pathloss [dB]']]
DS2_City_df = DS2_City_df.ffill()
DS2_City_df = DS2_City_df.dropna()

#Downtown (High Density) Dataframe:
DS2_Downtown_df = pd.read_csv('/content/drive/MyDrive/Downtown.csv')
DS2_Downtown_PL = pd.read_csv('/content/drive/MyDrive/Downtown Loss.csv')
DS2_Downtown_df.head(10)

DS2_Downtown_df['5G KPI PCell RF Pathloss [dB]'] = DS2_Downtown_PL['5G KPI PCell RF Pathloss [dB]']
DS2_Downtown_df = DS2_Downtown_df[DS2_Downtown_df['5G KPI PCell RF Pathloss [dB]'].notna()]
DS2_Downtown_df = DS2_Downtown_df[['5G KPI PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell Serving RSRP[dBm]', 'LTE KPI PCell Serving RSRQ[dB]', '5G KPI PCell RF Serving SS-RSRQ [dB]', '5G KPI PCell RF Best Beam SS-RSRP [dBm]', '5G KPI PCell RF Pathloss [dB]']]
DS2_Downtown_df = DS2_Downtown_df.ffill()
DS2_Downtown_df = DS2_Downtown_df.dropna()

import pickle as pkl

file = open("DS1_Rural.pkl", 'wb')
pkl.dump(DS1_Rural_df, file)
file.close()

file = open("DS1_Urban.pkl", 'wb')
pkl.dump(DS1_Urban_df, file)
file.close()

file = open("DS1_Suburban.pkl", 'wb')
pkl.dump(DS1_Suburban_df, file)
file.close()

file = open("DS2_Baseball.pkl", 'wb')
pkl.dump(DS2_Baseball_df, file)
file.close()

file = open("DS2_City-Wide.pkl", 'wb')
pkl.dump(DS2_City_df, file)
file.close()

file = open("DS2_Downtown.pkl", 'wb')
pkl.dump(DS2_Downtown_df, file)
file.close()

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!zip -r PickleFiles.zip PickleFiles/

from google.colab import files
files.download('PickleFiles.zip')
