# -*- coding: utf-8 -*-
"""Throughput Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NapMoRYkCFAwo25rJdz4lFP3dUgVxtxF
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

#Throughput Data
Throughput_df = pd.read_csv('/content/drive/MyDrive/THROUGHPUT DATA.csv')
Throughput_df.head(10)

Throughput_df = Throughput_df[['run_num', 'seq_num', 'abstractSignalStr', 'latitude', 'longitude', 'movingSpeed', 'compassDirection', 'nrStatus', 'lte_rssi', 'lte_rsrp', 'lte_rsrq', 'lte_rssnr', 'nr_ssRsrp', 'nr_ssRsrq', 'Throughput']]
Throughput_df = Throughput_df.dropna()
Throughput_df.head(10)

Throughput_small_df = Throughput_df[Throughput_df['Throughput'] < 300]
Throughput_medium_df = Throughput_df[(Throughput_df['Throughput'] >= 300) & (Throughput_df['Throughput'] <= 700)]
Throughput_large_df = Throughput_df[Throughput_df['Throughput'] > 700]

Throughput_small_df.head(10)

Throughput_medium_df.head(10)

Throughput_large_df.head(10)

import pickle as pkl

file = open("Throughput_Small.pkl", 'wb')
pkl.dump(Throughput_small_df, file)
file.close()

file = open("Throughput_Medium.pkl", 'wb')
pkl.dump(Throughput_medium_df, file)
file.close()

file = open("Throughput_Large.pkl", 'wb')
pkl.dump(Throughput_large_df, file)
file.close()

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!zip -r ThroughputData.zip ThroughputData/

from google.colab import files
files.download('ThroughputData.zip')